### PR TITLE
Updated installation guide along with options for different package m…

### PR DESCRIPTION
**Pull request by saisab29**
**What does this PR do?**
This PR provides an instruction to setup the project with the options for different package managers

Fixes #4

image

### CODE REVIEW

**Review by joonshakya — CHANGES_REQUESTED** [review]
To install packages using yarn, you just run command 
```bash
yarn
```
the command you wrote gives error Command "i" not found.
And you probably don't need to mention how to install pnpm, yarn, bun.
If they use them, they probably have them installed else they would just use npm

**Comment by saisab29** [comment]
Can you check it again?

**Review by joonshakya — CHANGES_REQUESTED** [review]
Can you remove install pnpm globally part and put installation and running the server in same subheading as installation? and also move the installation on top of contributing section

**Comment by saisab29** [comment]
> Can you remove install pnpm globally part and put installation and running the server in same subheading as installation? and also move the installation on top of contributing section

Do you want 'Running the server' also above the contributing section?

**Pull request merged**
